#!/usr/bin/env bash
#listing the multiples of 3 and 5 between 1 and 100 
count=1 
while [ $count -lt 101 ]
do 
	 if [ $((count%15)) = 0 ]
	then 
		echo "FizzBuzz"
	elif [ $((count%3)) = 0 ] 
	then
		echo "Fizz"
	elif [ $((count%5)) = 0 ]
	then
		echo "Buzz"
	else 
		echo " $count" 
	 fi

 
((count+=1))
done 
