#!/usr/bin/env bash
#using case for several arguments 

counter=1
while [ $counter -lt 21 ]
do 
	case $counter in 
	4) 
		echo $counter 
		echo "bad luck from China"
		;;
	9) 
		echo $counter 
		echo "bad luck from Japan"
		;;
	17) 
		echo $counter
		echo "bad luck from Italy"
		;;
	*)
		echo $counter 
		;;
	esac
	
	((counter+=1))

done 
