#!/usr/bin/env bash
# displays information about the holbertonschool file.

FILE="school"

if [ -e "$FILE" ]
then
    echo "school"
    if [ ! -s "$FILE" ]
    then
        echo "school"
    else
        echo "school"
    fi
    if [ -f "$FILE" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
